package com.example.aeron

import android.animation.ValueAnimator
import android.content.Context
import android.graphics.*
import android.graphics.drawable.GradientDrawable
import android.os.Bundle
import android.view.*
import android.widget.*
import androidx.appcompat.app.AppCompatActivity
import kotlin.math.cos
import kotlin.math.sin

class MainActivity : AppCompatActivity() {
    private val bg=Color.rgb(3,7,18); private val panel=Color.rgb(8,14,28)
    private val cyan=Color.rgb(56,189,248); private val purple=Color.rgb(168,85,247)
    private val blue=Color.rgb(59,130,246); private val green=Color.rgb(16,185,129)
    private val white=Color.WHITE; private val muted=Color.rgb(100,116,139)
    private lateinit var content:LinearLayout
    override fun onCreate(b:Bundle?){super.onCreate(b);window.statusBarColor=bg;window.navigationBarColor=bg;build();home()}
    private fun build(){val root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setBackgroundColor(bg)};content=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(18),dp(12),dp(18),dp(18))};root.addView(ScrollView(this).apply{isFillViewport=true;addView(content)},LinearLayout.LayoutParams(-1,0,1f));root.addView(nav());setContentView(root)}
    private fun header():View{return LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER_VERTICAL;setPadding(dp(10),dp(7),dp(8),dp(7));background=round(Color.rgb(11,17,32),30,Color.rgb(30,41,59));addView(TextView(this@MainActivity).apply{text="A";gravity=Gravity.CENTER;textSize=16f;setTextColor(Color.BLACK);typeface=Typeface.DEFAULT_BOLD;background=grad(cyan,purple)},LinearLayout.LayoutParams(dp(36),dp(36)));addView(LinearLayout(this@MainActivity).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(10),0,0,0);addView(tv("AERON",15f,white));addView(tv("AI COMPANION • CORE",9f,cyan))},LinearLayout.LayoutParams(0,-2,1f));addView(tv("✦",20f,cyan),LinearLayout.LayoutParams(dp(38),dp(38)));addView(TextView(this@MainActivity).apply{text="A";gravity=Gravity.CENTER;textSize=12f;setTextColor(white);background=round(Color.TRANSPARENT,50,cyan)},LinearLayout.LayoutParams(dp(32),dp(32)))}}
    private fun home(){clear();content.addView(header());content.addView(space(18));content.addView(tv("Good day.",13f,cyan));content.addView(space(4));content.addView(tv("How can AERON help?",27f,white));content.addView(space(16));content.addView(Orb(this),LinearLayout.LayoutParams(-1,dp(245)));content.addView(space(14));val s=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(16),dp(14),dp(16),dp(12));background=round(panel,20,Color.rgb(30,41,59))};s.addView(tv("●  AERON is ready",13f,green));s.addView(tv("Wake word: Hey AERON",11f,muted));s.addView(Wave(this),LinearLayout.LayoutParams(-1,dp(25)));content.addView(s);content.addView(space(20));content.addView(tv("QUICK ACTIONS",10f,muted));content.addView(space(10));row(action("⌕","Search","Find anything"){chat()},action("◇","Create","Generate media"){create()});row(action("◉","Voice","Talk to AERON"){voice()},action("▣","Files","Analyze files"){toast("File analysis ready")});content.addView(space(20));content.addView(tv("RECENT",10f,muted));content.addView(space(9));item("✦","Welcome to AERON","Your AI companion","Now")}
    private fun chat(){clear();content.addView(header());content.addView(space(20));content.addView(tv("CHAT",25f,white));content.addView(tv("Intelligent conversation",12f,muted));content.addView(space(18));content.addView(card("✦  I'm ready. What would you like to do?"));content.addView(space(12));item("✦","Ask anything","Get an intelligent answer","");item("⌕","Search the web","Get current information","");item("◇","Create media","Generate images and video","")}
    private fun voice(){clear();content.addView(header());content.addView(space(20));content.addView(tv("VOICE",25f,white));content.addView(tv("Talk naturally with AERON",12f,muted));content.addView(space(18));content.addView(Orb(this,true),LinearLayout.LayoutParams(-1,dp(310)));content.addView(space(14));content.addView(card("WAKE WORD\n\nHey AERON\n\nBackground wake-word detection is configured with your AERON model."))}
    private fun create(){clear();content.addView(header());content.addView(space(20));content.addView(tv("CREATE",25f,white));content.addView(tv("Bring your ideas to life",12f,muted));content.addView(space(18));item("✦","Image","Generate stunning visuals","");item("▶","Video","Create AI video","");item("◇","Edit","Transform your media","")}
    private fun memory(){clear();content.addView(tv("MEMORY",25f,white));content.addView(tv("Your AERON memory vault",12f,muted));content.addView(space(18));content.addView(card("MEMORY VAULT\n\nManage information AERON remembers about your conversations and preferences."));content.addView(space(12));item("◇","Preferences","Personal preferences","");item("✦","Conversations","Remembered context","");item("◉","Privacy","Control what AERON remembers","")}
    private fun settings(){clear();content.addView(tv("SETTINGS",25f,white));content.addView(tv("Customize your AERON experience",12f,muted));section("ACCOUNT","Account","Google, Facebook or phone");section("AERON CORE","AERON CORE","Personality and intelligence");section("VOICE & WAKE WORD","Voice & Wake Word","Hey AERON detection");section("APPEARANCE","Appearance","Theme and visual experience");section("MEMORY","Memory","Manage Memory Vault");section("PRIVACY","Privacy & Security","Data and permissions")}
    private fun section(sec:String,title:String,sub:String){content.addView(space(12));content.addView(tv(sec,9f,cyan));content.addView(space(7));item("›",title,sub,"")}
    private fun nav():View{return LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;setPadding(dp(8),dp(5),dp(8),dp(7));setBackgroundColor(bg);addView(n("⌂","Home"){home()});addView(n("✦","Chat"){chat()});addView(n("◉","Voice"){voice()});addView(n("◇","Memory"){memory()});addView(n("☰","Settings"){settings()})}}
    private fun n(i:String,t:String,a:()->Unit)=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;gravity=Gravity.CENTER;setOnClickListener{a()};addView(tv(i,19f,cyan));addView(tv(t,9f,muted));layoutParams=LinearLayout.LayoutParams(0,dp(55),1f)}
    private fun row(a:View,b:View){val r=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL};r.addView(a);r.addView(space(10,1));r.addView(b);content.addView(r);content.addView(space(10))}
    private fun action(i:String,t:String,d:String,a:()->Unit)=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(15),dp(14),dp(12),dp(12));background=round(panel,18,Color.rgb(30,41,59));setOnClickListener{a()};addView(tv(i,21f,cyan));addView(space(8));addView(tv(t,14f,white));addView(tv(d,10f,muted));layoutParams=LinearLayout.LayoutParams(0,dp(112),1f)}
    private fun item(i:String,t:String,s:String,time:String){val r=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER_VERTICAL;setPadding(dp(14),dp(12),dp(14),dp(12));background=round(panel,17,Color.rgb(30,41,59))};r.addView(tv(i,18f,cyan),LinearLayout.LayoutParams(dp(30),dp(30)));r.addView(LinearLayout(this@MainActivity).apply{orientation=LinearLayout.VERTICAL;addView(tv(t,13f,white));addView(tv(s,10f,muted))},LinearLayout.LayoutParams(0,-2,1f));if(time.isNotEmpty())r.addView(tv(time,9f,muted));val p=LinearLayout.LayoutParams(-1,-2);p.bottomMargin=dp(9);content.addView(r,p)}
    private fun card(s:String)=TextView(this).apply{text=s;textSize=14f;setTextColor(Color.rgb(203,213,225));setPadding(dp(17),dp(17),dp(17),dp(17));background=round(panel,20,Color.rgb(30,41,59))}
    private fun tv(s:String,z:Float,c:Int)=TextView(this).apply{text=s;textSize=z;setTextColor(c);typeface=Typeface.create("sans-serif",Typeface.BOLD);includeFontPadding=false;gravity=Gravity.CENTER_VERTICAL}
    private fun space(n:Int,w:Int=0)=Space(this).apply{layoutParams=LinearLayout.LayoutParams(dp(n),if(w==1)1 else dp(n))}
    private fun round(c:Int,r:Int,stroke:Int)=GradientDrawable().apply{setColor(c);cornerRadius=dp(r).toFloat();if(stroke!=0)setStroke(dp(1),stroke)}
    private fun grad(a:Int,b:Int)=GradientDrawable(GradientDrawable.Orientation.TL_BR,intArrayOf(a,b)).apply{shape=GradientDrawable.OVAL}
    private fun clear(){content.removeAllViews()};private fun dp(v:Int)= (v*resources.displayMetrics.density).toInt();private fun toast(s:String)=Toast.makeText(this,s,Toast.LENGTH_SHORT).show()
    private class Wave(c:Context):View(c){val p=Paint(1);var t=0f;init{p.color=Color.rgb(56,189,248);ValueAnimator.ofFloat(0f,1f).apply{duration=1100;repeatCount=-1;addUpdateListener{t=it.animatedValue as Float;invalidate()};start()}}override fun onDraw(c:Canvas){for(i in 0..17){val h=(5+15*(.5+.5*sin(i*.9+t*Math.PI*2))).toFloat();val x=width/(20f)*(i+1);c.drawRoundRect(x,height-h,x+4,height.toFloat(),3f,3f,p)}}}
    private class Orb(c:Context,val listen:Boolean=false):View(c){val p=Paint(1);var t=0f;init{ValueAnimator.ofFloat(0f,1f).apply{duration=3200;repeatCount=-1;addUpdateListener{t=it.animatedValue as Float;invalidate()};start()}}override fun onDraw(c:Canvas){val x=width/2f;val y=height/2f-8;val r=minOf(width,height)*.36f;p.shader=RadialGradient(x,y,r*1.8f,intArrayOf(Color.rgb(25,30,75),Color.rgb(5,8,20),Color.TRANSPARENT),null,Shader.TileMode.CLAMP);c.drawRect(0f,0f,width.toFloat(),height.toFloat(),p);p.shader=null;for(i in 0..3){p.style=Paint.Style.STROKE;p.strokeWidth=if(i==0)2.3f else 1.1f;p.color=if(i%2==0)Color.rgb(0,242,254) else Color.rgb(99,102,241);p.alpha=210-i*35;c.drawCircle(x,y,r*(.72f+i*.16f)+sin(t*6+i)*4,p)};val core=r*.58f;p.style=Paint.Style.FILL;p.alpha=255;p.shader=LinearGradient(x-core,y-core,x+core,y+core,intArrayOf(Color.rgb(59,130,246),Color.rgb(168,85,247)),null,Shader.TileMode.CLAMP);c.drawCircle(x,y,core,p);p.shader=null;p.style=Paint.Style.STROKE;p.strokeWidth=2f;p.color=Color.WHITE;c.drawCircle(x,y,core,p);p.style=Paint.Style.FILL;p.color=Color.WHITE;p.textSize=core*.58f;p.typeface=Typeface.DEFAULT_BOLD;p.textAlign=Paint.Align.CENTER;c.drawText("A",x,y+core*.2f,p);p.textSize=10f;p.color=Color.rgb(56,189,248);c.drawText(if(listen)"AERON LISTENING" else "AERON CORE",x,height-20f,p)}}
}
